import base64
import os

# Base64 encoded content - split into chunks to avoid escaping issues
encoded_content = '''
ImVzcGVjdXRpdmUgZGlzY292ZXJ5IHVzaW5nIFRhdmlseSBzZWFyY2ggQVBJIGFuZCBHZW1pbmkgZXh0cmFjdGlvbi4KClRoaXMgc2Vyd2ljZSBpbXBsZW1lbnRzIGEgc29waGlzdGljYXRlZCBleGVjdXRpdmUgZGlzY292ZXJ5IHBpcGVsaW5lIHdpdGg6Ci0gUXVlcnkgc2VyaWVzIGdlbmVyYXRpb24gKGdlbmVyaWMgLT4gc3BlY2lmaWMpIHdpdGggcXVhbGl0eS1iYXNlZCBkZWVwZW5pbmcKLSBVUkwgZGVkdXBsaWNhdGlvbiB3aXRoIGRvbWFpbiBwYWdlIHByZXNlcnZhdGlvbgotIFJlc3VsdCBwcmlvcml0aXphdGlvbiBieSBzb3VyY2UgKExpbmtlZEluID4gY29tcGFueSA+IG5ld3MgPiBvdGhlcikKLSBHZW1pbmktYmFzZWQgc3RyaWN0IGV4dHJhY3Rpb24gKG5vIGhhbGx1Y2luYXRpb24pCi0gU291cmNlLXdlaWdodGVkIGNvbmZpZGVuY2Ugc2NvcmluZwotIEZ1enp5IG5hbWUtYmFzZWQgZGVkdXBsaWNhdGlvbiBhdCBlbnRpdHkgbGV2ZWwK
'''.strip()

decoded = base64.b64decode(encoded_content).decode('utf-8')
print(decoded)

